// src/App.tsx
import { Route, HashRouter as Router, Routes } from 'react-router-dom';
import './App.css';
import AppBar from "./components/MuAppBar";
import MuSalaryYear from './components/MuSalaryYear';
import MuSalaryMonth from './components/MuSalaryMonth';
import MuCostYear from './components/MuCostYear';

function App() {
  return (
    <div className="App">
      <Router>
        <AppBar />
        <Routes>
          <Route path='/' element={<MuSalaryYear />} />
          <Route path='/salary/' element={<MuSalaryYear />} />
          <Route path='/salary/:year' element={<MuSalaryYear />} />
          <Route path='/salary/:year/:month' element={<MuSalaryMonth />} />
          <Route path='/cost/' element={<MuCostYear />} />
          <Route path='/cost/:year' element={<MuCostYear />} />
        </Routes>
      </Router>
    </div>
  );
}

export default App;

// front/sail/App.svelte
<script lang="ts">
  import "bulma/css/bulma.css";
  import AppBar from "./lib/AppBar.svelte";
  import Router from "svelte-spa-router";
  import Home from "./routes/Home.svelte";
  import SalaryYear from "./routes/SalaryYear.svelte";
  import SalaryMonth from "./routes/SalaryMonth.svelte";
  import CostYear from "./routes/Cost.svelte";

  const routes = {
    "/": Home,
    "/:year": Home,
    "/salary/:year": SalaryYear,
    "/salary/:year/:month": SalaryMonth,
    "/cost/:year": CostYear,
  };
</script>

<AppBar />
<main>
  <Router {routes} />
</main>
